const checkpoint = (label, ...any) => ({ label, any });
const free = (id, topic, prompt, solution, checkpoints, difficulty = 2) => ({ id, topic, prompt, solution, checkpoints, difficulty, type: "free" });
const choice = (id, topic, prompt, options, answer, solution, difficulty = 1) => ({ id, topic, prompt, options, answer, solution, difficulty, type: "choice" });

const olsDerivation = [
    free("od01", "ols", "Write the OLS objective in matrix notation and identify the dimensions of each object.", "For y in R^n, X in R^(n x p), and beta in R^p, minimize L(beta) = ||y - X beta||_2^2 = (y - X beta)'(y - X beta).", [checkpoint("Squared-residual objective", "||y-xbeta||", "(y-xbeta)'(y-xbeta)", "sum of squared residuals"), checkpoint("Dimensions", "y in r^n", "x is n by p", "beta in r^p")]),
    free("od02", "ols", "Expand (y - X beta)'(y - X beta) into four terms, then simplify.", "L(beta) = y'y - y'X beta - beta'X'y + beta'X'X beta. The two middle terms are equal scalars, so L(beta) = y'y - 2 beta'X'y + beta'X'X beta.", [checkpoint("Four-term expansion", "y'y", "yty"), checkpoint("Cross term", "-2beta'x'y", "-2 beta transpose x transpose y"), checkpoint("Quadratic term", "beta'x'xbeta", "beta transpose x transpose x beta")]),
    free("od03", "ols", "Differentiate the OLS objective with respect to beta.", "The gradient is nabla_beta L = -2X'(y - X beta) = 2X'X beta - 2X'y.", [checkpoint("Gradient", "-2x'(y-xbeta)", "2x'xbeta-2x'y", "2 x transpose x beta - 2 x transpose y")]),
    free("od04", "ols", "Derive the OLS normal equations from the first-order condition.", "Set -2X'(y - X beta_hat) = 0. Therefore X'X beta_hat = X'y. These are the normal equations.", [checkpoint("Zero gradient", "gradient equal to zero", "=0"), checkpoint("Normal equations", "x'xbeta=x'y", "x transpose x beta equals x transpose y")]),
    free("od05", "ols", "Derive the closed-form OLS estimator and state the condition needed for this form.", "From X'X beta_hat = X'y, if X has full column rank so X'X is invertible, beta_hat = (X'X)^(-1)X'y.", [checkpoint("Normal equations", "x'xbeta=x'y", "normal equations"), checkpoint("Full column rank", "full column rank", "rank(x)=p"), checkpoint("Closed form", "(x'x)^-1x'y", "inverse of x transpose x")]),
    free("od06", "ols", "What happens to the OLS solution when X does not have full column rank? Give the minimum-norm solution.", "The coefficients are not unique because X'X is singular. The fitted values are still unique. The Moore-Penrose solution beta_hat = X^+ y is the minimum-Euclidean-norm least-squares solution.", [checkpoint("Singularity", "singular", "not invertible"), checkpoint("Nonunique coefficients", "coefficients are not unique", "multiple solutions"), checkpoint("Pseudoinverse", "x+ y", "moore penrose", "pseudoinverse")]),
    free("od07", "ols", "Derive the projection-matrix representation of the fitted values.", "Substitute beta_hat into y_hat = X beta_hat: y_hat = X(X'X)^(-1)X'y = Hy, where H is the orthogonal projector onto the column space of X.", [checkpoint("Substitution", "x(x'x)^-1x'y", "x inverse"), checkpoint("Hat matrix", "h=x(x'x)^-1x'", "projection matrix"), checkpoint("Column space", "column space of x", "col(x)")]),
    free("od08", "ols", "Prove that OLS residuals are orthogonal to every column of X.", "The first-order condition gives X'(y - X beta_hat) = X'e_hat = 0. Hence e_hat is orthogonal to Col(X), including the intercept column when one is present.", [checkpoint("Residual definition", "e=y-xbeta", "residual"), checkpoint("Orthogonality equation", "x'e=0", "x transpose e equals zero"), checkpoint("Column space", "orthogonal to", "column space")]),
    free("od09", "ols", "Derive the conditional expectation of beta_hat under y = X beta + epsilon and E[epsilon|X] = 0.", "beta_hat = beta + (X'X)^(-1)X'epsilon. Conditioning on X gives E[beta_hat|X] = beta + (X'X)^(-1)X'E[epsilon|X] = beta, so OLS is conditionally unbiased.", [checkpoint("Estimator decomposition", "beta+(x'x)^-1x'epsilon", "beta plus"), checkpoint("Zero conditional error", "e[epsilon|x]=0", "conditional mean zero"), checkpoint("Unbiased conclusion", "e[betahat|x]=beta", "unbiased")]),
    free("od10", "ols", "Derive Var(beta_hat | X) under homoskedastic errors with Var(epsilon|X) = sigma^2 I.", "Using beta_hat - beta = (X'X)^(-1)X'epsilon, Var(beta_hat|X) = (X'X)^(-1)X'(sigma^2 I)X(X'X)^(-1) = sigma^2(X'X)^(-1).", [checkpoint("Linear variance setup", "(x'x)^-1x'", "variance"), checkpoint("Homoskedastic covariance", "sigma^2i", "sigma squared i"), checkpoint("Final covariance", "sigma^2(x'x)^-1", "sigma squared inverse")]),
    free("od11", "ols", "Derive the core Gauss-Markov comparison for another linear unbiased estimator beta_tilde = Cy.", "Unbiasedness requires CX = I. Write C = (X'X)^(-1)X' + D, where DX = 0. Then Var(beta_tilde|X) - Var(beta_hat|X) = sigma^2 DD', which is positive semidefinite. OLS is BLUE.", [checkpoint("Unbiasedness constraint", "cx=i", "c x equals i"), checkpoint("Decomposition", "c=(x'x)^-1x'+d", "dx=0"), checkpoint("PSD variance difference", "sigma^2dd'", "positive semidefinite"), checkpoint("BLUE", "blue", "best linear unbiased")], 3),
    free("od12", "ols", "Show why OLS residuals sum to zero when the design contains an intercept.", "With an intercept, the all-ones vector 1 is a column of X. Since X'e_hat = 0, the intercept component gives 1'e_hat = sum_i e_hat_i = 0.", [checkpoint("Intercept column", "ones", "1 is a column"), checkpoint("Normal equation", "x'e=0", "orthogonal"), checkpoint("Zero sum", "sum", "1'e=0")]),
    free("od13", "ols", "Prove that the OLS hat matrix H is symmetric and idempotent.", "H = X(X'X)^(-1)X'. Symmetry follows because (X'X)^(-1) is symmetric, so H' = H. Multiplying gives H^2 = X(X'X)^(-1)(X'X)(X'X)^(-1)X' = H.", [checkpoint("Hat matrix", "h=x(x'x)^-1x'", "hat matrix"), checkpoint("Symmetric", "h'=h", "symmetric"), checkpoint("Idempotent", "h^2=h", "idempotent")]),
    free("od14", "ols", "Derive the residual-maker matrix and state two of its properties.", "M = I - H, so e_hat = My. Because H is symmetric and idempotent, M is also symmetric and idempotent. Also MX = 0 and rank(M) = n - p under full column rank.", [checkpoint("Residual maker", "m=i-h", "e=my"), checkpoint("Symmetric/idempotent", "symmetric", "idempotent"), checkpoint("Annihilates X", "mx=0", "rank")]),
    free("od15", "ols", "Derive the unbiased estimator of sigma squared in the classical linear model.", "RSS = e_hat'e_hat = epsilon'Mepsilon. Since E[epsilon'Mepsilon|X] = sigma^2 tr(M) = sigma^2(n-p), the unbiased estimator is s^2 = RSS/(n-p).", [checkpoint("RSS quadratic form", "e'e", "epsilon'mepsilon"), checkpoint("Trace degrees of freedom", "tr(m)=n-p", "n-p"), checkpoint("Estimator", "rss/(n-p)", "squared residuals divided")]),
    free("od16", "ols", "Derive the sampling distribution of beta_hat under Gaussian errors.", "If epsilon|X ~ N(0, sigma^2 I), then beta_hat = beta + (X'X)^(-1)X'epsilon is an affine transformation of a Gaussian vector. Therefore beta_hat|X ~ N(beta, sigma^2(X'X)^(-1)).", [checkpoint("Gaussian assumption", "normal", "gaussian"), checkpoint("Affine transformation", "affine", "linear transformation"), checkpoint("Distribution", "n(beta,sigma^2(x'x)^-1)", "mean beta")]),
    free("od17", "ols", "Derive omitted-variable bias for a regression that omits Z from y = X beta + Z gamma + epsilon.", "Regressing y only on X gives beta_tilde = (X'X)^(-1)X'y = beta + (X'X)^(-1)X'Z gamma + (X'X)^(-1)X'epsilon. Conditional bias is (X'X)^(-1)X'Z gamma.", [checkpoint("Substitute true model", "x'z gamma", "omit"), checkpoint("Estimator decomposition", "beta+(x'x)^-1x'z gamma", "beta plus"), checkpoint("Bias term", "(x'x)^-1x'z gamma", "conditional bias")], 3),
    free("od18", "ols", "State and derive the Frisch-Waugh-Lovell result for the coefficient on X2 in y = X1 beta1 + X2 beta2 + epsilon.", "Let M1 = I - X1(X1'X1)^(-1)X1'. Residualize y and X2 against X1. Then beta2_hat = (X2'M1X2)^(-1)X2'M1y, identical to the X2 block coefficient in the full regression.", [checkpoint("Residual maker", "m1=i-x1", "residualize"), checkpoint("Residualize both", "m1y", "m1x2"), checkpoint("Coefficient", "(x2'm1x2)^-1x2'm1y", "same coefficient")], 3),
    free("od19", "ols", "Derive the weighted least-squares estimator for positive-definite weight matrix W.", "Minimize (y-X beta)'W(y-X beta). The gradient is -2X'W(y-X beta). Setting it to zero gives X'WX beta_hat = X'Wy, hence beta_hat_WLS = (X'WX)^(-1)X'Wy.", [checkpoint("Weighted objective", "(y-xbeta)'w(y-xbeta)", "weighted squared"), checkpoint("Weighted normal equations", "x'wxbeta=x'wy", "x transpose w"), checkpoint("Estimator", "(x'wx)^-1x'wy", "wls")]),
    free("od20", "ols", "Derive the one-regressor OLS slope and intercept formulas from the normal equations.", "With an intercept, the normal equations imply alpha_hat = y_bar - beta_hat x_bar. Substitution into the slope equation yields beta_hat = sum_i (x_i-x_bar)(y_i-y_bar) / sum_i (x_i-x_bar)^2 = Cov_sample(x,y)/Var_sample(x).", [checkpoint("Intercept", "ybar-betahat xbar", "mean y minus"), checkpoint("Centered numerator", "(xi-xbar)(yi-ybar)", "covariance"), checkpoint("Centered denominator", "(xi-xbar)^2", "variance")])
];

const derivationTopics = [
    { id: "ols", name: "OLS", summary: "Normal equations, projections, sampling properties, and extensions.", steps: ["Write L(beta) = (y - X beta)'(y - X beta).", "Differentiate: nabla L = -2X'(y - X beta).", "Set the gradient to zero: X'X beta_hat = X'y.", "Under full column rank, beta_hat = (X'X)^(-1)X'y.", "Interpret X beta_hat as the projection of y onto Col(X)."], questions: olsDerivation },
    { id: "black-scholes", name: "Black–Scholes", summary: "Delta hedging, the pricing PDE, risk-neutral valuation, and the closed form.", steps: ["Assume geometric Brownian motion dS = mu S dt + sigma S dW.", "Apply Ito's lemma to V(S,t).", "Form Pi = V - Delta S and choose Delta = V_S to remove dW risk.", "No arbitrage forces V_t + .5 sigma^2 S^2 V_SS + rS V_S - rV = 0.", "Solve with the terminal payoff; for a call C = S N(d1) - K e^(-rT) N(d2)."], questions: [
        free("bs01", "black-scholes", "Derive the Black–Scholes PDE using a delta-hedged portfolio.", "Ito gives dV = (V_t + mu S V_S + .5 sigma^2 S^2 V_SS)dt + sigma S V_S dW. Hold Pi = V - Delta S with Delta = V_S. The diffusion cancels, so no arbitrage requires dPi = rPi dt, yielding V_t + .5 sigma^2 S^2 V_SS + rS V_S - rV = 0.", [checkpoint("Ito expansion", "ito", "v_t", "vss"), checkpoint("Delta hedge", "delta=v_s", "delta equals"), checkpoint("No-arbitrage return", "r", "riskless"), checkpoint("PDE", "v_t+.5sigma^2s^2v_ss+rsv_s-rv=0", "black scholes pde")], 3),
        free("bs02", "black-scholes", "Explain why the stock's real-world drift mu disappears from the Black–Scholes PDE.", "The delta hedge cancels the common Brownian exposure in the option and stock. Once locally riskless, the portfolio must earn r by no arbitrage. The mu terms cancel, so price depends on risk-neutral rather than physical drift.", [checkpoint("Hedge cancels risk", "delta hedge", "brownian"), checkpoint("Risk-free return", "risk free", "earn r"), checkpoint("Drift cancellation", "mu cancels", "drift disappears")]),
        free("bs03", "black-scholes", "Derive d1 and d2 for a European call and state the closed form.", "For tau to expiry, d1 = [ln(S/K) + (r + .5 sigma^2)tau]/(sigma sqrt(tau)) and d2 = d1 - sigma sqrt(tau). Then C = S N(d1) - K e^(-r tau)N(d2), with dividends handled by replacing S with S e^(-q tau) and r by r-q in d1.", [checkpoint("d1", "ln(s/k)", ".5sigma^2", "sigma sqrt"), checkpoint("d2", "d2=d1-sigma", "d1 minus"), checkpoint("Call price", "sn(d1)-ke^-r", "s n(d1)")]),
        free("bs04", "black-scholes", "Show the risk-neutral distribution used to price the terminal stock value.", "Under Q, dS = rSdt + sigma S dW^Q. Ito applied to ln S gives ln S_T ~ N(ln S_0 + (r - .5 sigma^2)T, sigma^2 T), hence S_T = S_0 exp((r-.5 sigma^2)T + sigma sqrt(T)Z).", [checkpoint("Risk-neutral drift", "ds=rsdt", "drift r"), checkpoint("Log correction", "r-.5sigma^2", "minus half"), checkpoint("Lognormal terminal value", "lognormal", "sqrt(t)z")]),
        free("bs05", "black-scholes", "Give the terminal and boundary conditions for a European call and explain their role.", "At expiry C(S,T) = max(S-K,0). At S=0, C=0. As S grows, C approaches S - K e^(-r tau). These conditions select the economically relevant solution of the pricing PDE.", [checkpoint("Terminal payoff", "max(s-k,0)", "payoff"), checkpoint("Zero-stock boundary", "c(0", "s=0"), checkpoint("Large-stock boundary", "s-ke^-r", "approaches s minus")])
    ]},
    { id: "gamma-pnl", name: "Gamma P&L Approximation", summary: "Second-order option P&L and the realized-versus-implied volatility link.", steps: ["Apply a second-order Taylor expansion to V(S,t).", "Keep Delta dS, .5 Gamma(dS)^2, and Theta dt.", "For a delta-hedged position, remove the first-order spot term.", "Use the Black–Scholes PDE to replace theta and financing terms.", "Obtain P&L approximately .5 Gamma S^2 (sigma_realized^2 - sigma_implied^2)dt."], questions: [
        free("gp01", "gamma-pnl", "Derive the second-order approximation for an option's change in value.", "Taylor expansion gives Delta V approximately V_S Delta S + V_t Delta t + .5 V_SS(Delta S)^2. In Greek notation: Delta V approximately Delta Delta S + Theta Delta t + .5 Gamma(Delta S)^2, ignoring higher-order and cross terms.", [checkpoint("Delta term", "delta delta s", "v_s"), checkpoint("Theta term", "theta delta t", "v_t"), checkpoint("Gamma term", ".5gamma", "one half gamma")]),
        free("gp02", "gamma-pnl", "Derive the P&L of a discretely delta-hedged option over one short interval.", "For long option and short Delta shares, financing aside, P&L approximately Theta Delta t + .5 Gamma(Delta S)^2 because the option's Delta Delta S is offset by the hedge's -Delta Delta S.", [checkpoint("Option Taylor expansion", "theta", "gamma"), checkpoint("Delta cancellation", "cancel", "delta hedged"), checkpoint("Remaining P&L", "theta delta t+.5gamma", "gamma pnl")]),
        free("gp03", "gamma-pnl", "Connect delta-hedged Gamma P&L to realized and implied variance.", "Using (Delta S)^2 approximately S^2 sigma_realized^2 Delta t and the Black–Scholes theta/financing relation based on sigma_implied, hedged P&L approximately .5 Gamma S^2 (sigma_realized^2 - sigma_implied^2)Delta t.", [checkpoint("Squared move", "(delta s)^2", "s^2 sigma"), checkpoint("Variance spread", "realized", "implied"), checkpoint("Final approximation", ".5gamma s^2", "sigma_realized^2-sigma_implied^2")]),
        free("gp04", "gamma-pnl", "Explain the sign of Gamma P&L for a long option when realized volatility exceeds implied volatility.", "A long vanilla option has positive Gamma. If realized variance exceeds the implied variance paid, .5 Gamma S^2(realized variance - implied variance)dt is positive, before costs and hedge slippage.", [checkpoint("Positive gamma", "positive gamma", "long option"), checkpoint("Variance comparison", "realized", "implied"), checkpoint("Positive P&L", "positive", "profit")]),
        free("gp05", "gamma-pnl", "State the important errors omitted by the Gamma P&L approximation.", "It omits higher Greeks and cross terms, volatility changes, jumps, finite hedge intervals, transaction costs, funding/dividends, and model error. Large moves make the local Taylor approximation less reliable.", [checkpoint("Higher-order terms", "higher", "vanna", "volga"), checkpoint("Discrete/jump risk", "jumps", "discrete"), checkpoint("Costs/model error", "transaction costs", "model error")])
    ]},
    { id: "atm-call", name: "ATM Call Approximation", summary: "The short-dated at-the-money call approximation and its assumptions.", steps: ["Start with C = S N(d1) - K N(d2) for r=q=0.", "Set S=K, so d1=.5 sigma sqrt(T), d2=-.5 sigma sqrt(T).", "Use N(x) approximately .5 + phi(0)x near zero.", "Subtract the two CDF terms.", "Obtain C approximately S sigma sqrt(T/(2 pi))."], questions: [
        free("ac01", "atm-call", "Derive C_ATM approximately S sigma sqrt(T/(2 pi)) from Black–Scholes.", "With r=q=0 and S=K, d1=.5 sigma sqrt(T), d2=-.5 sigma sqrt(T). Thus C=S[N(a)-N(-a)] with a=.5 sigma sqrt(T). Since N(a) approximately .5 + a/sqrt(2pi), the difference is 2a/sqrt(2pi), giving C approximately S sigma sqrt(T/(2pi)).", [checkpoint("ATM d-values", "d1=.5sigma", "d2=-.5sigma"), checkpoint("Normal CDF expansion", "n(a)", "sqrt(2pi)"), checkpoint("Final approximation", "s sigma sqrt(t/(2pi))", "sσ√")]),
        choice("ac02", "atm-call", "Which assumptions are built into the simplest ATM call approximation?", ["S=K, zero rates/dividends, and small sigma sqrt(T)", "Deep ITM, high rates, and long maturity", "Only zero volatility", "American exercise and discrete dividends"], 0, "The clean formula uses S=K, r=q=0, and a first-order normal-CDF expansion, which is best when sigma sqrt(T) is small."),
        free("ac03", "atm-call", "Derive the corresponding ATM straddle approximation.", "Put-call parity gives C=P when S=K and r=q=0. Therefore straddle = C+P approximately 2S sigma sqrt(T/(2pi)) = S sigma sqrt(2T/pi).", [checkpoint("ATM call equals put", "c=p", "put call parity"), checkpoint("Double the call", "2s", "twice"), checkpoint("Final straddle", "s sigma sqrt(2t/pi)", "sqrt(2/pi)")]),
        free("ac04", "atm-call", "How does the approximation let you recover implied volatility from an observed ATM call price?", "Rearrange C approximately S sigma sqrt(T/(2pi)): sigma approximately (C/S)sqrt(2pi/T).", [checkpoint("Rearrangement", "sigma=(c/s)", "c divided by s"), checkpoint("Time scaling", "sqrt(2pi/t)", "inverse square root time")]),
        free("ac05", "atm-call", "Explain why ATM option value scales approximately with square-root time, not linearly with time.", "Under diffusion, the standard deviation of the stock move is proportional to sigma sqrt(T). An ATM option captures the positive part of this roughly symmetric move, so its leading time value inherits the sqrt(T) scaling.", [checkpoint("Diffusion scale", "sqrt(t)", "standard deviation"), checkpoint("Positive-part payoff", "positive part", "option"), checkpoint("Not linear", "square root", "not linear")])
    ]},
    { id: "mom", name: "Method of Moments", summary: "Estimate parameters by matching sample and population moments.", steps: ["Choose as many population moments as unknown parameters.", "Write each moment as a function of theta.", "Replace population moments with sample analogues.", "Solve the resulting equations for theta_hat.", "Check identification and parameter constraints."], questions: [
        free("mm01", "mom", "Derive the Method of Moments estimator for the rate lambda of an Exponential(lambda) distribution.", "E[X]=1/lambda. Set the sample mean X_bar equal to 1/lambda_hat and solve: lambda_hat_MOM = 1/X_bar.", [checkpoint("Population mean", "e[x]=1/lambda", "mean is 1"), checkpoint("Moment match", "xbar=1/lambda", "sample mean"), checkpoint("Estimator", "lambda=1/xbar", "inverse sample mean")]),
        free("mm02", "mom", "Derive MOM estimators for Uniform(0, theta) using the first moment.", "For X~Uniform(0,theta), E[X]=theta/2. Set X_bar=theta_hat/2, so theta_hat_MOM=2X_bar.", [checkpoint("Population mean", "theta/2", "mean"), checkpoint("Match sample mean", "xbar", "sample mean"), checkpoint("Estimator", "2xbar", "two times")]),
        free("mm03", "mom", "Derive MOM estimators for the mean and variance parameters of a Normal(mu, sigma squared) distribution.", "Use E[X]=mu and E[X^2]=mu^2+sigma^2. Then mu_hat=X_bar and sigma_hat^2=(1/n)sum X_i^2-X_bar^2=(1/n)sum(X_i-X_bar)^2.", [checkpoint("First moment", "mu=xbar", "sample mean"), checkpoint("Second moment", "e[x^2]=mu^2+sigma^2", "second moment"), checkpoint("Variance estimator", "1/n", "squared deviations")]),
        free("mm04", "mom", "Explain exactly identification in Method of Moments.", "With k parameters, exactly identified MOM uses k independent moment equations. The mapping from parameters to moments must be locally one-to-one, commonly requiring a full-rank Jacobian, so the equations have a unique local solution.", [checkpoint("Same number", "k", "same number"), checkpoint("Independent moments", "independent", "rank"), checkpoint("Unique solution", "one-to-one", "unique")]),
        free("mm05", "mom", "Contrast Method of Moments with maximum likelihood.", "MOM matches selected moments and may be simple and robust but does not generally use the full distribution. MLE maximizes the full likelihood and is often asymptotically efficient when the model is correct, but can be more sensitive to misspecification.", [checkpoint("Moment matching", "moments", "match"), checkpoint("Full likelihood", "likelihood", "full distribution"), checkpoint("Efficiency tradeoff", "efficient", "misspecification")])
    ]},
    { id: "mle", name: "Maximum Likelihood", summary: "Likelihood construction, score equations, curvature, and uncertainty.", steps: ["Write L(theta)=product_i f(x_i|theta).", "Take logs to turn products into sums.", "Differentiate to form the score.", "Solve score(theta_hat)=0 and check curvature/boundaries.", "Use observed or expected Fisher information for standard errors."], questions: [
        free("ml01", "mle", "Derive the Bernoulli maximum-likelihood estimator for p.", "The likelihood is p^(sum x_i)(1-p)^(n-sum x_i). The log-likelihood is S log p +(n-S)log(1-p). Setting S/p-(n-S)/(1-p)=0 gives p_hat=S/n=X_bar.", [checkpoint("Likelihood", "p^", "(1-p)"), checkpoint("Score", "s/p", "n-s"), checkpoint("Estimator", "p=xbar", "s/n")]),
        free("ml02", "mle", "Derive the MLE of lambda for iid Exponential(lambda) observations.", "l(lambda)=n log lambda-lambda sum x_i. The score n/lambda-sum x_i=0 gives lambda_hat=n/sum x_i=1/X_bar. The second derivative -n/lambda^2 is negative.", [checkpoint("Log likelihood", "n log lambda", "-lambda sum"), checkpoint("Score", "n/lambda", "sum x"), checkpoint("Estimator", "1/xbar", "n/sum"), checkpoint("Maximum check", "negative", "second derivative")]),
        free("ml03", "mle", "Derive the Gaussian MLEs of mu and sigma squared.", "For iid N(mu,sigma^2), maximizing the log-likelihood gives mu_hat=X_bar. Substituting this into the variance score gives sigma_hat_MLE^2=(1/n)sum(X_i-X_bar)^2. The denominator is n, not n-1.", [checkpoint("Mean estimator", "mu=xbar", "sample mean"), checkpoint("Variance estimator", "1/n", "squared deviations"), checkpoint("MLE denominator", "not n-1", "denominator n")]),
        free("ml04", "mle", "Derive the asymptotic variance of a regular one-dimensional MLE.", "Under regularity conditions, sqrt(n)(theta_hat-theta_0) converges in distribution to N(0,I_1(theta_0)^(-1)). Thus Var(theta_hat) approximately 1/[n I_1(theta_0)] = I_n(theta_0)^(-1).", [checkpoint("Root-n limit", "sqrt(n)", "converges"), checkpoint("Normal limit", "normal", "n(0"), checkpoint("Inverse information", "1/(n", "information inverse")], 3),
        free("ml05", "mle", "Show why maximizing likelihood is equivalent to minimizing negative log-likelihood.", "Log is strictly increasing, so argmax_theta L(theta)=argmax_theta log L(theta). Multiplying the objective by -1 reverses max to min, giving argmin_theta[-log L(theta)]. For iid data, the log also converts the product of densities into a sum.", [checkpoint("Monotone log", "strictly increasing", "monotonic"), checkpoint("Sign reversal", "negative", "minimize"), checkpoint("Product to sum", "product", "sum")])
    ]}
];

const modelTopics = [
    { id: "ols-model", name: "OLS", summary: "Linear prediction, assumptions, diagnostics, interpretation, and failure modes.", steps: ["Model E[y|X] as a linear function X beta.", "Fit by minimizing squared residuals.", "Interpret coefficients conditionally on included predictors.", "Check residual structure, leverage, and collinearity.", "Use robust inference or a different model when assumptions fail."], questions: [
        choice("om01", "ols-model", "Which condition is required for OLS coefficients to be conditionally unbiased?", ["E[epsilon|X]=0", "Errors must be Gaussian", "R-squared must exceed 0.5", "Every predictor must be independent"], 0, "Conditional mean zero, E[epsilon|X]=0, is the key exogeneity condition. Gaussian errors are not needed for unbiasedness."),
        free("om02", "ols-model", "Interpret beta_j in a multiple linear regression.", "beta_j is the expected change in y associated with a one-unit increase in x_j, holding the other included predictors fixed, under the model's linear conditional-mean specification.", [checkpoint("One-unit change", "one unit", "unit increase"), checkpoint("Hold others fixed", "holding", "conditional"), checkpoint("Expected outcome", "expected", "mean")]),
        choice("om03", "ols-model", "What does severe multicollinearity usually do?", ["Inflates coefficient variance without necessarily biasing OLS", "Always biases every coefficient upward", "Makes residuals nonzero in sample", "Guarantees poor predictions"], 0, "Multicollinearity makes individual coefficients imprecise by inflating variance; it does not by itself create bias."),
        free("om04", "ols-model", "Distinguish heteroskedasticity's effect on OLS coefficients from its effect on classical standard errors.", "With exogeneity, OLS coefficients remain unbiased/consistent under heteroskedasticity, but the homoskedastic variance formula is wrong. Use heteroskedasticity-robust standard errors for valid large-sample inference.", [checkpoint("Coefficient property", "unbiased", "consistent"), checkpoint("Standard errors wrong", "standard errors", "variance formula"), checkpoint("Robust remedy", "robust", "heteroskedasticity consistent")]),
        free("om05", "ols-model", "Explain the difference between a high-leverage point and an influential point.", "Leverage measures unusual predictor values through the diagonal h_ii of the hat matrix. Influence measures how much fitted results change when a point is removed. High leverage can become influential when paired with a substantial residual.", [checkpoint("Leverage definition", "predictor", "h_ii"), checkpoint("Influence definition", "change", "removed"), checkpoint("Residual interaction", "residual", "high leverage")])
    ]},
    { id: "logistic", name: "Logistic Regression", summary: "Log-odds, likelihood, classification thresholds, and calibration.", steps: ["Model log[p/(1-p)] = X beta.", "Map scores to probabilities with the sigmoid.", "Fit by Bernoulli maximum likelihood / cross-entropy.", "Choose thresholds based on decision costs, not convention alone.", "Evaluate discrimination and calibration separately."], questions: [
        free("lr01", "logistic", "Explain why logistic regression uses log-odds as a linear function.", "Probabilities are bounded in [0,1], while log-odds log[p/(1-p)] range over the real line. Modeling log-odds as X beta and applying the inverse-logit guarantees valid probabilities.", [checkpoint("Bounded probabilities", "bounded", "0 and 1"), checkpoint("Unbounded log odds", "real line", "unbounded"), checkpoint("Inverse logit", "sigmoid", "inverse logit")]),
        free("lr02", "logistic", "Interpret a logistic-regression coefficient beta_j.", "Holding other variables fixed, a one-unit increase in x_j changes log-odds by beta_j and multiplies the odds by exp(beta_j). It does not generally change probability by a constant amount.", [checkpoint("Log-odds change", "log odds", "beta"), checkpoint("Odds ratio", "exp(beta", "multiplies odds"), checkpoint("Conditional interpretation", "holding", "not constant probability")]),
        choice("lr03", "logistic", "Why is there usually no closed-form logistic-regression estimator?", ["The score equations are nonlinear in beta", "The sigmoid is not differentiable", "Labels are always noisy", "The likelihood is linear"], 0, "The log-likelihood is smooth and concave, but its score equations are nonlinear, so iterative optimization is required."),
        free("lr04", "logistic", "Distinguish discrimination from calibration for a probability classifier.", "Discrimination measures ranking/separation, often with ROC AUC. Calibration asks whether predicted probabilities match observed frequencies. A model can rank well but produce poorly calibrated probabilities.", [checkpoint("Ranking", "ranking", "auc"), checkpoint("Frequency accuracy", "observed frequency", "probabilities match"), checkpoint("Can differ", "can", "poorly calibrated")]),
        free("lr05", "logistic", "How should you select a classification threshold?", "Choose a threshold using false-positive/false-negative costs, class prevalence, operational constraints, and the desired precision-recall tradeoff. A default of 0.5 is not universally optimal.", [checkpoint("Decision costs", "cost", "false positive"), checkpoint("Prevalence/constraints", "prevalence", "constraint"), checkpoint("Not always .5", "0.5", "not")])
    ]},
    { id: "ridge", name: "Ridge", summary: "L2 shrinkage, conditioning, effective degrees of freedom, and tuning.", steps: ["Standardize predictors.", "Minimize RSS + lambda||beta||_2^2.", "Use beta_hat=(X'X+lambda I)^(-1)X'y.", "Accept bias to reduce variance.", "Tune lambda by validation and leave the intercept unpenalized."], questions: [
        free("rg01", "ridge", "What does the Ridge penalty do geometrically and statistically?", "The L2 constraint is a Euclidean ball. Its smooth boundary shrinks coefficients continuously toward zero. This introduces bias but can substantially reduce variance, especially with correlated predictors.", [checkpoint("L2 geometry", "ball", "l2"), checkpoint("Shrinkage", "toward zero", "shrink"), checkpoint("Bias variance", "bias", "variance")]),
        choice("rg02", "ridge", "Does Ridge usually set coefficients exactly to zero?", ["No, it generally shrinks without exact sparsity", "Yes, every penalized coefficient becomes zero", "Only with standardized predictors", "Only for correlated predictors"], 0, "The smooth L2 penalty usually produces small but nonzero coefficients."),
        free("rg03", "ridge", "Why should predictors be standardized before Ridge?", "The penalty acts on coefficient magnitudes. Without standardization, a variable's measurement scale determines how strongly its coefficient is penalized. Standardization puts predictors on a comparable scale.", [checkpoint("Penalty on magnitude", "coefficient magnitude", "penalty"), checkpoint("Scale dependence", "scale", "units"), checkpoint("Comparable scale", "standardize", "comparable")]),
        free("rg04", "ridge", "Explain how Ridge helps with multicollinearity.", "Adding lambda I shifts the eigenvalues of X'X away from zero, improving conditioning. Directions with little data variation receive stronger shrinkage, lowering unstable coefficient variance.", [checkpoint("Eigenvalue shift", "eigenvalue", "lambda"), checkpoint("Conditioning", "conditioning", "singular"), checkpoint("Variance reduction", "variance", "stable")]),
        free("rg05", "ridge", "How is lambda selected and what happens at its extremes?", "Use cross-validation on the target loss. At lambda=0 Ridge equals OLS; as lambda approaches infinity, penalized coefficients approach zero. The intercept is usually excluded from the penalty.", [checkpoint("Cross validation", "cross validation", "validation"), checkpoint("Lambda zero", "lambda=0", "ols"), checkpoint("Lambda infinity", "infinity", "zero"), checkpoint("Intercept", "intercept", "not penalized")])
    ]},
    { id: "lasso", name: "Lasso", summary: "L1 sparsity, feature selection, instability, and optimization.", steps: ["Standardize predictors.", "Minimize RSS + lambda||beta||_1.", "Use coordinate descent or another convex optimizer.", "Expect exact zeros at corners of the L1 region.", "Validate stability when predictors are correlated."], questions: [
        free("la01", "lasso", "Why can Lasso produce exactly zero coefficients?", "The L1 constraint has corners on coordinate axes and the absolute-value penalty is nondifferentiable at zero. Loss contours often first touch the feasible region at a corner, producing sparse solutions.", [checkpoint("L1 corners", "corner", "l1"), checkpoint("Nondifferentiable", "nondifferentiable", "absolute"), checkpoint("Sparse result", "zero", "sparse")]),
        choice("la02", "lasso", "How does Lasso often behave with a group of highly correlated predictors?", ["It may select one somewhat arbitrarily and discard others", "It always gives them identical coefficients", "It becomes equivalent to unregularized OLS", "It cannot be fit"], 0, "Lasso selection can be unstable among strongly correlated predictors; Elastic Net can encourage grouped retention."),
        free("la03", "lasso", "Contrast Lasso and Ridge in terms of sparsity and prediction.", "Lasso's L1 penalty can set coefficients exactly to zero, aiding selection. Ridge's L2 penalty retains all variables and often behaves more stably with dense signals or correlated predictors. Which predicts better is data-dependent.", [checkpoint("Lasso sparsity", "lasso", "zero"), checkpoint("Ridge dense", "ridge", "retains"), checkpoint("Data dependent", "data", "cross validation")]),
        free("la04", "lasso", "What is the soft-thresholding operation in orthonormal-design Lasso?", "For an unpenalized coefficient z_j, the Lasso solution is sign(z_j) max(|z_j|-lambda,0), up to objective-scaling conventions. It shrinks magnitude and clips sufficiently small values to zero.", [checkpoint("Sign", "sign", "sgn"), checkpoint("Threshold", "max", "lambda"), checkpoint("Zeroing", "zero", "small")]),
        free("la05", "lasso", "What is Elastic Net and when is it useful?", "Elastic Net combines L1 and L2 penalties. It preserves sparsity while adding Ridge-like stabilization and can retain groups of correlated predictors more reliably than pure Lasso.", [checkpoint("Both penalties", "l1", "l2"), checkpoint("Sparsity", "sparse", "zero"), checkpoint("Correlated groups", "correlated", "group")])
    ]},
    { id: "svm", name: "SVM", summary: "Margins, hinge loss, support vectors, kernels, and hyperparameters.", steps: ["Choose a separating hyperplane f(x)=w'x+b.", "Maximize margin or minimize hinge loss plus regularization.", "Only points on/inside the margin become support vectors.", "Use kernels to represent nonlinear boundaries implicitly.", "Tune C and kernel parameters by validation."], questions: [
        free("sv01", "svm", "Explain maximum margin and why only support vectors determine the boundary.", "The geometric margin is inversely proportional to ||w||. Maximizing it chooses the widest separating slab. Points strictly outside the margin have zero hinge loss and zero dual weight, so only on-margin or violating points affect the solution.", [checkpoint("Margin norm", "1/||w||", "norm"), checkpoint("Widest separator", "maximize", "widest"), checkpoint("Support vectors", "hinge", "dual weight")]),
        free("sv02", "svm", "What does the SVM parameter C control?", "C controls the penalty for margin violations relative to margin width. Large C prioritizes fitting training observations with a narrower margin; small C permits more violations for stronger regularization and a wider margin.", [checkpoint("Violation penalty", "margin violation", "penalty"), checkpoint("Large C", "large c", "narrow"), checkpoint("Small C", "small c", "wide")]),
        choice("sv03", "svm", "What is the kernel trick?", ["Computing inner products in an implicit feature space", "Randomly deleting support vectors", "Turning labels into probabilities", "Standardizing every feature"], 0, "A kernel evaluates feature-space inner products without explicitly constructing the potentially high-dimensional features."),
        free("sv04", "svm", "Explain gamma in an RBF-kernel SVM.", "For K(x,z)=exp(-gamma||x-z||^2), large gamma creates very local influence and a more flexible boundary; small gamma creates broad influence and a smoother boundary. It interacts strongly with C.", [checkpoint("RBF form", "exp", "distance"), checkpoint("Large gamma", "large gamma", "local"), checkpoint("Small gamma", "small gamma", "smooth")]),
        free("sv05", "svm", "Why should features usually be standardized for SVMs?", "Margins and kernels depend on dot products or distances. A large-scale feature can dominate that geometry solely because of its units, so standardization prevents scale from determining the boundary.", [checkpoint("Distance geometry", "distance", "dot product"), checkpoint("Dominating scale", "dominate", "units"), checkpoint("Standardization", "standard", "scale")])
    ]},
    { id: "lda", name: "LDA", summary: "Gaussian class models with shared covariance and linear boundaries.", steps: ["Assume X|Y=k is Gaussian with mean mu_k.", "Use one covariance Sigma shared by every class.", "Combine class likelihoods with priors via Bayes' rule.", "Cancel common quadratic terms.", "Classify using linear discriminant scores."], questions: [
        free("ld01", "lda", "State LDA's generative assumptions and explain why its boundary is linear.", "LDA assumes X|Y=k ~ N(mu_k,Sigma) with class-specific means but a shared covariance. In the log posterior ratio, x'Sigma^(-1)x terms cancel between classes, leaving an affine function of x and therefore a linear boundary.", [checkpoint("Gaussian classes", "normal", "gaussian"), checkpoint("Shared covariance", "shared covariance", "same covariance"), checkpoint("Quadratic cancellation", "cancel", "quadratic"), checkpoint("Linear boundary", "linear", "affine")]),
        free("ld02", "lda", "Write the LDA discriminant score for class k.", "delta_k(x)=x'Sigma^(-1)mu_k - .5 mu_k'Sigma^(-1)mu_k + log pi_k. Predict the class with the largest score.", [checkpoint("Linear term", "x'sigma^-1mu", "inverse covariance"), checkpoint("Mean quadratic", "-.5", "mu"), checkpoint("Prior", "log pi", "class prior")]),
        choice("ld03", "lda", "When can LDA outperform logistic regression?", ["When Gaussian/shared-covariance assumptions are reasonable and data are limited", "Whenever classes are perfectly balanced", "Only when there are two features", "Never"], 0, "Its stronger generative assumptions can reduce variance when they are approximately correct, especially with limited samples."),
        free("ld04", "lda", "How do class priors affect an LDA boundary?", "The log prior log pi_k enters each discriminant score as an additive term. Increasing a class prior expands the region assigned to that class, all else equal.", [checkpoint("Log prior term", "log", "prior"), checkpoint("Boundary shift", "expand", "shift")]),
        free("ld05", "lda", "What fails when the covariance estimate is singular, and what can you do?", "The discriminant requires Sigma^(-1), so a singular or ill-conditioned covariance is unstable. Use shrinkage/regularized LDA, dimension reduction, feature selection, or a pseudoinverse.", [checkpoint("Inverse problem", "inverse", "singular"), checkpoint("Shrinkage", "shrink", "regularized"), checkpoint("Alternative remedy", "dimension", "pseudoinverse", "feature selection")])
    ]},
    { id: "qda", name: "QDA", summary: "Class-specific covariance models and flexible quadratic boundaries.", steps: ["Assume Gaussian features within each class.", "Estimate a separate covariance Sigma_k for every class.", "Retain class-specific quadratic terms in log posteriors.", "Obtain curved decision boundaries.", "Regularize covariance estimates when samples are limited."], questions: [
        free("qd01", "qda", "Why does QDA produce a quadratic decision boundary?", "QDA uses class-specific covariance matrices. The x'Sigma_k^(-1)x terms differ by class and therefore do not cancel in the log posterior comparison, leaving a quadratic function of x.", [checkpoint("Class covariance", "class specific", "different covariance"), checkpoint("No cancellation", "do not cancel", "remain"), checkpoint("Quadratic term", "x'sigma", "quadratic")]),
        free("qd02", "qda", "Contrast the bias-variance tradeoff of QDA and LDA.", "QDA is more flexible and can have lower bias when class covariances differ, but estimating one covariance per class raises variance and sample requirements. LDA pools covariance, increasing bias but reducing variance.", [checkpoint("QDA flexibility", "flexible", "lower bias"), checkpoint("QDA variance", "higher variance", "more data"), checkpoint("LDA pooling", "shared", "pool")]),
        choice("qd03", "qda", "When does QDA reduce to LDA?", ["When all class covariance matrices are equal", "When all class means are zero", "When priors are equal", "When there are exactly two classes"], 0, "Equal class covariance matrices make the quadratic terms common, so they cancel and the boundary becomes linear."),
        free("qd04", "qda", "Why is QDA fragile in high dimensions?", "Each class covariance has p(p+1)/2 parameters and must be inverted. When p is large relative to class sample size, estimates have high variance or become singular.", [checkpoint("Parameter count", "p(p+1)/2", "quadratic number"), checkpoint("Per-class samples", "class sample", "sample size"), checkpoint("Singular/high variance", "singular", "high variance")]),
        free("qd05", "qda", "Name two principled ways to regularize QDA.", "Shrink each class covariance toward a pooled covariance or diagonal matrix; reduce dimensions before fitting; constrain covariance structure; or add a positive ridge term lambda I before inversion.", [checkpoint("Shrinkage target", "pooled", "diagonal", "lambda i"), checkpoint("Second remedy", "dimension", "constrain", "ridge")])
    ]},
    { id: "bagging", name: "Bagging", summary: "Bootstrap aggregation, variance reduction, out-of-bag estimates, and random forests.", steps: ["Draw bootstrap samples from the training set.", "Fit one high-variance learner per sample.", "Average predictions or vote across learners.", "Use out-of-bag observations for validation.", "Decorrelate trees with feature subsampling in a random forest."], questions: [
        free("bg01", "bagging", "Why does bagging primarily reduce variance?", "Averaging noisy estimators cancels idiosyncratic fluctuations. If each learner has variance sigma^2 and pairwise correlation rho, the large-ensemble variance approaches rho sigma^2, so lower correlation yields more reduction.", [checkpoint("Averaging", "average", "fluctuation"), checkpoint("Correlation", "correlation", "rho"), checkpoint("Variance reduction", "variance", "reduce")]),
        choice("bg02", "bagging", "Which base learner benefits most naturally from bagging?", ["A deep, unstable decision tree", "A highly stable linear regression", "A fixed constant predictor", "A deterministic lookup with no sampling variation"], 0, "Bagging is most useful for unstable, high-variance learners such as deep trees."),
        free("bg03", "bagging", "What is an out-of-bag estimate?", "Each bootstrap sample omits about 36.8% of training observations. For each observation, aggregate predictions only from learners whose bootstrap sample omitted it, creating an internal validation estimate without a separate holdout.", [checkpoint("Omitted bootstrap cases", "36.8", "omitted"), checkpoint("Only nontraining trees", "did not include", "out of bag"), checkpoint("Validation", "validation", "holdout")]),
        free("bg04", "bagging", "How does a random forest differ from ordinary bagged trees?", "Both bootstrap observations, but random forests also sample a subset of candidate features at each split. This decorrelates trees, often lowering ensemble variance further.", [checkpoint("Bootstrap commonality", "bootstrap", "both"), checkpoint("Feature subsampling", "subset", "features"), checkpoint("Decorrelation", "decorrelate", "correlation")]),
        free("bg05", "bagging", "Does adding more trees to a bagged ensemble usually cause classical overfitting?", "With fixed tree-generation settings, test error generally converges as trees are added rather than turning upward from ensemble size alone. More trees cost computation; tree depth and other base-learner choices still matter.", [checkpoint("Convergence", "converge", "stabilize"), checkpoint("Not classic overfit", "not", "overfit"), checkpoint("Other complexity controls", "depth", "base learner")])
    ]},
    { id: "boosting", name: "Boosting", summary: "Sequential error correction, gradient descent in function space, and regularization.", steps: ["Initialize a simple constant prediction.", "Compute residuals or negative loss gradients.", "Fit a weak learner to that correction signal.", "Add the learner with a shrinkage factor.", "Use validation and early stopping to select ensemble size."], questions: [
        free("bo01", "boosting", "Contrast boosting with bagging.", "Bagging fits learners independently on bootstrap samples and averages them, mainly reducing variance. Boosting fits learners sequentially to residuals or gradients, building a strong model that often reduces bias as well as variance.", [checkpoint("Parallel vs sequential", "independent", "sequential"), checkpoint("Bootstrap average", "bootstrap", "average"), checkpoint("Residual/gradient", "residual", "gradient")]),
        free("bo02", "boosting", "Explain gradient boosting as gradient descent in function space.", "At each iteration, compute the negative gradient of the loss with respect to current predictions. Fit a base learner to these pseudo-residuals and add a scaled version to the current function, taking an approximate descent step.", [checkpoint("Negative gradient", "negative gradient", "pseudo residual"), checkpoint("Fit learner", "fit", "base learner"), checkpoint("Add scaled step", "learning rate", "add")]),
        choice("bo03", "boosting", "What does a smaller learning rate usually require?", ["More boosting rounds", "Fewer observations", "No regularization", "A larger test set"], 0, "Shrinkage makes each update smaller, so more rounds are typically required; the combination often generalizes better."),
        free("bo04", "boosting", "How do tree depth and learning rate interact in boosted trees?", "Tree depth controls interaction complexity per learner; learning rate controls each learner's contribution. Deep trees plus a high learning rate can fit noise quickly. Shallower trees and smaller steps are more regularized but may need more rounds.", [checkpoint("Depth complexity", "depth", "interaction"), checkpoint("Learning-rate contribution", "learning rate", "step"), checkpoint("Overfit interaction", "noise", "more rounds")]),
        free("bo05", "boosting", "Why is early stopping a form of regularization?", "Every boosting round expands the fitted function. Stopping at the validation-loss minimum limits effective model complexity before later learners begin fitting noise.", [checkpoint("Rounds increase complexity", "round", "complexity"), checkpoint("Validation minimum", "validation", "minimum"), checkpoint("Prevents noise fit", "noise", "overfit")])
    ]},
    { id: "nn", name: "Neural Networks", summary: "Forward computation, backpropagation, optimization, and generalization.", steps: ["Compose affine layers with nonlinear activations.", "Compute predictions and a task-appropriate loss.", "Backpropagate gradients with the chain rule.", "Update parameters with SGD or an adaptive optimizer.", "Control generalization with validation, weight decay, dropout, and early stopping."], questions: [
        free("nn01", "nn", "Why are nonlinear activations necessary between neural-network layers?", "Without nonlinear activations, a composition of affine layers is still a single affine transformation, regardless of depth. Nonlinearities let the network represent curved and piecewise nonlinear functions.", [checkpoint("Linear composition", "single", "linear", "affine"), checkpoint("Nonlinear expressiveness", "nonlinear", "represent")]),
        free("nn02", "nn", "Explain backpropagation without implementation details.", "Backpropagation applies the chain rule from the loss backward through the computation graph. It reuses intermediate derivatives to efficiently compute the gradient of the loss with respect to every parameter.", [checkpoint("Chain rule", "chain rule", "derivative"), checkpoint("Backward graph", "backward", "computation graph"), checkpoint("All parameter gradients", "every parameter", "gradient")]),
        choice("nn03", "nn", "What commonly causes vanishing gradients?", ["Repeated multiplication by small derivatives through many layers", "Using a validation set", "Large mini-batches alone", "One-hot labels"], 0, "Products of derivatives below one can decay exponentially with depth, making early-layer updates tiny."),
        free("nn04", "nn", "Contrast batch, stochastic, and mini-batch gradient descent.", "Batch uses all training examples per update and has low gradient noise but high cost. Stochastic uses one example and is noisy. Mini-batch uses a subset, balancing compute efficiency, vectorization, and useful gradient noise.", [checkpoint("Batch", "all", "batch"), checkpoint("Stochastic", "one", "noisy"), checkpoint("Mini-batch", "subset", "balance")]),
        free("nn05", "nn", "Name four neural-network regularization methods and explain one.", "Examples include weight decay, dropout, early stopping, data augmentation, label smoothing, and capacity reduction. Weight decay penalizes large weights, encouraging smoother, lower-complexity solutions.", [checkpoint("At least four methods", "weight decay", "dropout", "early stopping", "augmentation"), checkpoint("Explanation", "penal", "random", "validation", "synthetic")])
    ]},
    { id: "regularization", name: "Regularization", summary: "How each model controls complexity and why validation matters.", steps: ["Identify the model's main source of variance.", "Choose a penalty or structural constraint.", "Put scale-sensitive features on comparable units.", "Tune strength using held-out data or cross-validation.", "Report the full preprocessing and tuning pipeline."], questions: [
        free("re01", "regularization", "Explain regularization through the bias-variance tradeoff.", "Regularization restricts the fitted model or penalizes complexity. It usually increases bias but can lower variance enough to reduce expected test error, especially when data are noisy or predictors are numerous.", [checkpoint("Restrict complexity", "complex", "penalty"), checkpoint("Bias increases", "bias", "increase"), checkpoint("Variance/test error", "variance", "test error")]),
        free("re02", "regularization", "Map the main regularization control to Ridge, Lasso, SVM, boosting, and neural networks.", "Ridge uses an L2 penalty; Lasso uses L1; SVM uses C (inverse regularization convention); boosting uses learning rate, depth, rounds, and early stopping; neural networks use weight decay, dropout, augmentation, capacity, and early stopping.", [checkpoint("Ridge/Lasso", "ridge", "l2", "lasso", "l1"), checkpoint("SVM", "svm", "c"), checkpoint("Boosting", "learning rate", "early stopping"), checkpoint("Neural network", "dropout", "weight decay")]),
        choice("re03", "regularization", "Why must preprocessing be fit inside each cross-validation training fold?", ["To prevent information leakage from validation folds", "To guarantee zero training error", "To eliminate all variance", "To make labels balanced automatically"], 0, "Fitting scaling, imputation, or selection before splitting leaks validation information into training and biases performance estimates."),
        free("re04", "regularization", "How are covariance shrinkage in LDA/QDA and coefficient shrinkage in regression conceptually related?", "Both trade some bias for lower estimation variance. Regression shrinks coefficients; regularized discriminant analysis shrinks noisy covariance estimates toward a stable target such as a diagonal or pooled covariance.", [checkpoint("Bias variance", "bias", "variance"), checkpoint("Coefficient shrinkage", "coefficient", "regression"), checkpoint("Covariance target", "covariance", "diagonal", "pooled")]),
        free("re05", "regularization", "Why should hyperparameters be chosen on validation data rather than the test set?", "Validation data are used for model selection. The test set must remain untouched until the pipeline is fixed so it provides an approximately unbiased final estimate of generalization. Repeated test-set tuning overfits the test set.", [checkpoint("Validation selects", "validation", "selection"), checkpoint("Test untouched", "test", "untouched"), checkpoint("Unbiased generalization", "generalization", "unbiased", "overfit")])
    ]}
];

export const BANKS = { derivations: derivationTopics, models: modelTopics };
export const getQuestions = moduleName => BANKS[moduleName].flatMap(topic => topic.questions);
